"""Build the research ledger (ledger.csv and LEDGER.md) from the entries below.

Every hypothesis tested for the sleeve gets one row, pass or fail, so results persist across sessions.
Add new rows at the end of ENTRIES and rerun: python build_ledger.py
"""
from __future__ import annotations

import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
FIELDS = ["id", "date", "family", "hypothesis", "instruments", "timeframe", "hold", "design", "held_out", "fresh",
          "verdict", "script", "notes"]

# design / held_out / fresh: mean R per trade (t) unless stated; "n/a" where a set was not run.
ENTRIES: list[dict] = [
    # ---- 24 September 2026 ----
    dict(id="S01", date="2026-09-24", family="chart structure", hypothesis="Pullback, failed move and bracket structures, mechanical", instruments="20 pairs 2022-23; BTC 2017-26", timeframe="4h", hold="to 3R or stop",
         design="about 0R (-0.06R, n=1219)", held_out="+0.01R (n=1425)", fresh="n/a", verdict="fail", script="bt.py, edge.py", notes="Stops under 0.5% lose about 0.66R a trade"),
    dict(id="S02", date="2026-09-24", family="regime", hypothesis="Pullback in low volatility boost", instruments="BTC", timeframe="4h", hold="to 3R",
         design="-0.13R (n=160) 2019-22", held_out="+0.02R (n=172) 2023-26", fresh="n/a", verdict="fail", script="regime.py", notes="Boost dropped from the prompts"),
    dict(id="S03", date="2026-09-24", family="intraday BTC", hypothesis="Eight intraday tests: US-session momentum, fading and breaking stretched levels, Asia-range sweep, funding windows, hour of day, weekly alt momentum", instruments="BTC 1m 2017-26", timeframe="1m to 1h", hold="intraday",
         design="-0.04R to -0.42R", held_out="none positive in both halves", fresh="n/a", verdict="fail", script="(session scripts, 24 Sep)", notes="Costs of 0.04% to 0.14% against stops near 0.8%"),
    dict(id="S04", date="2026-09-24", family="trend", hypothesis="BTC time-series momentum, 14 and 28-day blend, 40% volatility target", instruments="BTC 2013-26", timeframe="daily", hold="weeks",
         design="Sharpe 2.91, 1.20, 1.43, 1.04 by period", held_out="positive every period", fresh="n/a", verdict="positive (parked at the owner's call)", script="(session, 24 Sep)", notes="Long-only Sharpe about 1.29, max drawdown 31%"),
    # ---- 25 September 2026, morning ----
    dict(id="S05", date="2026-09-25", family="weekend", hypothesis="Weekend gap continuation (Friday CME close to Sunday open)", instruments="BTC; alts", timeframe="1h", hold="to 3R",
         design="+0.17R (BTC 2022-23)", held_out="+0.22R (BTC, n=38); alts negative", fresh="n/a", verdict="retired", script="gap.py", notes="CME trades 24/7 since 29 May 2026, so the gap no longer forms"),
    dict(id="S06", date="2026-09-25", family="levels", hypothesis="the owner's method: tested support or trendline, stop 0.25 ATR beyond, re-enter at next support", instruments="BTC, ETH, SOL, XRP", timeframe="4h levels, 1h execution", hold="to 3R, 240h",
         design="longs -0.26R (t -5.2), shorts -0.41R (t -8.6)", held_out="longs -0.45R, shorts -0.21R", fresh="n/a", verdict="fail", script="support.py", notes="Re-entries worse than first entries"),
    dict(id="S07", date="2026-09-25", family="levels", hypothesis="Same levels, stop 1.0 ATR beyond (F2) or entry at the sweep (F3)", instruments="BTC, ETH, SOL, XRP", timeframe="4h / 1h", hold="to 3R",
         design="F2 longs -0.07R, shorts -0.18R", held_out="F2 longs -0.22R, shorts +0.09R", fresh="n/a", verdict="fail", script="support_variants.py", notes="Wide stops cut the loss by about 0.2R; stop buffer rule kept"),
    dict(id="S08", date="2026-09-25", family="levels", hypothesis="G: level entries only in the direction of the 14/28-day trend", instruments="BTC, ETH, SOL, XRP", timeframe="4h", hold="to 3R",
         design="aligned -0.095R vs all -0.092R", held_out="no gain", fresh="n/a", verdict="fail", script="loop1.py", notes=""),
    dict(id="S09", date="2026-09-25", family="reversal", hypothesis="C: capitulation (2.5 sigma daily move) buy early / after confirmation; blow-off short", instruments="BTC, ETH, SOL, XRP", timeframe="daily, 1h execution", hold="10 days",
         design="early longs -0.11R; confirm about 0R", held_out="early longs -0.52R (t -2.9); shorts negative", fresh="n/a", verdict="fail", script="loop1.py", notes=""),
    dict(id="S10", date="2026-09-25", family="volatility", hypothesis="N: NR7 daily bracket", instruments="BTC, ETH, SOL, XRP; then 10 majors", timeframe="daily, 4h execution", hold="3 days",
         design="+0.08R (t 2.8), halves +0.24R then -0.03R", held_out="-0.03R", fresh="n/a", verdict="fail", script="loop1.py, nr7_broad.py", notes="Decayed after 2020"),
    # ---- 25 September 2026, loop batch 1 ----
    dict(id="R01", date="2026-09-25", family="range", hypothesis="Range fade (grid) at tested 1h range edges, target mid", instruments="BTC 5m exec; ETH, SOL, XRP 1h", timeframe="1h", hold="48h",
         design="-0.43R (t -7.6)", held_out="-0.38R", fresh="-0.26R (t -6.5)", verdict="fail", script="range_grid.py", notes="Wins 21.7% vs about 28% for a random walk: edges break more often than chance"),
    dict(id="R02", date="2026-09-25", family="range", hypothesis="Range fade, target far edge", instruments="as R01", timeframe="1h", hold="48h",
         design="-0.52R", held_out="-0.45R", fresh="n/a", verdict="fail", script="range_grid.py", notes=""),
    dict(id="R03", date="2026-09-25", family="range", hypothesis="Range break, stop just inside", instruments="as R01 + six fresh", timeframe="1h", hold="to 3R, 48h",
         design="-1.11R", held_out="-1.04R", fresh="-1.25R", verdict="fail", script="range_break.py", notes="Breaks rarely follow through"),
    dict(id="R04", date="2026-09-25", family="range", hypothesis="Range break, stop at range mid", instruments="as R03", timeframe="1h", hold="to 3R, 48h",
         design="+0.01R", held_out="-0.01R", fresh="-0.06R", verdict="fail", script="range_break.py", notes=""),
    dict(id="F01", date="2026-09-25", family="funding", hypothesis="Fade funding extremes (top/bottom 5% of 90 days)", instruments="BTC, ETH 2020-23; 8 coins 2025-26", timeframe="8h funding, 4h execution", hold="5 days",
         design="-0.01R (t -0.1)", held_out="-0.12R", fresh="n/a", verdict="fail", script="funding_extremes.py", notes="Literature: funding is a one-month crash-risk state, not a short-term signal"),
    dict(id="T01", date="2026-09-25", family="trend", hypothesis="Multi-horizon trend ensemble, long only (5 to 360-day closing highs, trailing midpoint stop)", instruments="BTC, ETH, SOL, XRP; six fresh", timeframe="daily, 4h execution", hold="median 3.3 days, tail to months",
         design="Sharpe 1.53 (t 5.3); +1.27R a trade (t 8.9)", held_out="Sharpe 1.49 (t 2.5)", fresh="Sharpe 1.18 (t 3.5)", verdict="PASS (daily, not intraday)", script="trend_ensemble.py", notes="Passes with the 0.5% stop rail; first run failed fresh on one DOT trade with a near-zero stop"),
    dict(id="T02", date="2026-09-25", family="trend", hypothesis="Trend ensemble, exit on daily close below stop", instruments="as T01", timeframe="daily", hold="median 6 days",
         design="Sharpe 0.50 (t 1.7)", held_out="Sharpe 0.92", fresh="Sharpe 0.76", verdict="fail", script="trend_ensemble.py", notes="Design t below 3"),
    dict(id="T03", date="2026-09-25", family="continuation", hypothesis="MAX-10: long the morning after a 10-day closing high, 1 ATR stop, exit next morning", instruments="as T01", timeframe="daily, 4h execution", hold="24h rolling",
         design="+0.11R (t 4.7); halves +0.23R, +0.06R", held_out="+0.08R (t 2.4)", fresh="+0.06R (t 2.8)", verdict="PASS (24h hold, not intraday)", script="trend_ensemble.py, max10_checks.py", notes="Holds at lookbacks 5 to 30, taker entry, 12 of 15 years; pooled out-of-sample t 3.5"),
    dict(id="T04", date="2026-09-25", family="reversal", hypothesis="MIN-10: buy a 10-day closing low", instruments="as T01", timeframe="daily", hold="24h",
         design="-0.01R", held_out="-0.02R", fresh="+0.01R", verdict="fail", script="trend_ensemble.py", notes=""),
    dict(id="T05", date="2026-09-25", family="continuation", hypothesis="SHORT-10: sell a 10-day closing low", instruments="as T01", timeframe="daily", hold="24h",
         design="-0.02R", held_out="0.00R", fresh="-0.03R (t -2.2)", verdict="fail", script="max10_checks.py", notes="Shorts do not pay"),
    dict(id="T06", date="2026-09-25", family="trend", hypothesis="Trend ensemble with three lookbacks (20, 60, 150) for manual use", instruments="as T01", timeframe="daily", hold="median 10 days",
         design="+2.10R (t 4.6); Sharpe 1.03", held_out="+0.94R (t 1.9); Sharpe 1.00", fresh="+0.90R (t 4.7)", verdict="supports T01", script="trend_subset.py", notes="Robustness variant"),
    # ---- loop batch 2 ----
    dict(id="H01", date="2026-09-25", family="harmonic", hypothesis="Harmonic XABCD (Gartley, Bat, Alt Bat, Butterfly, Crab, Deep Crab), PRZ limit, ZigZag 8", instruments="BTC, ETH, SOL, XRP; six fresh", timeframe="1h", hold="5 days, split targets",
         design="-0.14R (t -1.9)", held_out="-0.12R", fresh="-0.12R", verdict="fail", script="tv_indicators.py", notes="LonesomeTheBlue script is closed source; standard ratios used"),
    dict(id="H02", date="2026-09-25", family="harmonic", hypothesis="Harmonic XABCD", instruments="as H01", timeframe="4h", hold="5 days",
         design="-0.30R (t -2.7)", held_out="-0.15R", fresh="-0.02R", verdict="fail", script="tv_indicators.py", notes=""),
    dict(id="L01", date="2026-09-25", family="trendline", hypothesis="LuxAlgo Trendlines with Breaks (exact published logic), stop 1.5 ATR, 3R", instruments="as H01", timeframe="1h", hold="5 days",
         design="-0.13R (t -2.4)", held_out="-0.12R", fresh="-0.06R", verdict="fail", script="tv_indicators.py", notes=""),
    dict(id="L02", date="2026-09-25", family="trendline", hypothesis="LuxAlgo trendline breaks", instruments="as H01", timeframe="4h", hold="5 days",
         design="+0.13R (t 2.4); halves +0.41R, -0.03R", held_out="-0.03R", fresh="+0.11R (t 3.0)", verdict="fail", script="tv_indicators.py", notes="Longs +0.15R: the long-trend effect again"),
    dict(id="R05", date="2026-09-25", family="range", hypothesis="Range deviation reclaim (sweep, close back inside), target mid", instruments="as R03", timeframe="1h signal, 5m BTC", hold="48h",
         design="-0.29R (t -3.9)", held_out="-0.39R", fresh="-0.28R", verdict="fail", script="range_deviation.py", notes="BTC on 5m -0.58R"),
    dict(id="R06", date="2026-09-25", family="range", hypothesis="Range deviation reclaim, target far edge", instruments="as R03", timeframe="1h", hold="48h",
         design="-0.41R", held_out="-0.36R", fresh="-0.34R", verdict="fail", script="range_deviation.py", notes=""),
    dict(id="R07", date="2026-09-25", family="range", hypothesis="Deviation reclaim, only with the 14/28-day trend", instruments="as R03", timeframe="1h", hold="48h",
         design="-0.46R", held_out="-0.32R", fresh="-0.26R", verdict="fail", script="range_deviation.py", notes=""),
    dict(id="R08", date="2026-09-25", family="range", hypothesis="Range fade, only with the 14/28-day trend", instruments="as R03", timeframe="1h", hold="48h",
         design="-0.43R", held_out="-0.45R", fresh="-0.21R", verdict="fail", script="range_deviation.py", notes=""),
    dict(id="T07", date="2026-09-25", family="trend", hypothesis="Trend ensemble shorts (Donchian mirror)", instruments="as T01", timeframe="daily", hold="days",
         design="+0.15R (t 2.2); halves -0.09R, +0.21R", held_out="-0.08R", fresh="+0.09R", verdict="fail", script="remaining_lines.py", notes="Paid in 2018 (+1.35R) and 2022 (+0.30R) only"),
    dict(id="T08", date="2026-09-25", family="trend", hypothesis="Trend shorts only while BTC's market trend is down", instruments="as T01", timeframe="daily", hold="days",
         design="+0.45R (t 3.7); halves +0.22R, +0.48R", held_out="-0.11R", fresh="+0.12R (t 2.6)", verdict="fail", script="orb.py", notes="Held-out negative"),
    dict(id="E01", date="2026-09-25", family="macro", hypothesis="CPI and FOMC bracket at the release, 0.25% legs, stop at the reference, 3R", instruments="BTC 5m, 2017-26", timeframe="5m", hold="2h",
         design="-0.75R (t -5.2)", held_out="-0.65R", fresh="n/a", verdict="fail", script="remaining_lines.py", notes="Whipsaw at releases"),
    dict(id="E02", date="2026-09-25", family="macro", hypothesis="CPI and FOMC bracket, 0.5% legs", instruments="as E01", timeframe="5m", hold="2h",
         design="-0.45R", held_out="-0.31R", fresh="n/a", verdict="fail", script="remaining_lines.py", notes=""),
    dict(id="X01", date="2026-09-25", family="reversal", hypothesis="Liquidation-spike fade (6 sigma 5m bar)", instruments="BTC 5m 2016-26", timeframe="5m", hold="2h",
         design="-0.67R (t -15)", held_out="-1.12R", fresh="n/a", verdict="fail", script="remaining_lines.py", notes="Median stop 0.29%: costs dominate and spikes continue"),
    dict(id="X02", date="2026-09-25", family="lead-lag", hypothesis="BTC to alt lead-lag after a 2 sigma BTC 15m move", instruments="9 alts 15m 2025-26", timeframe="15m", hold="15m and 1h",
         design="-0.15% a trade", held_out="-0.16%", fresh="n/a", verdict="fail", script="remaining_lines.py", notes="Gross about zero"),
    dict(id="O01", date="2026-09-25", family="opening range", hypothesis="ORB-5 at the US open (first 5m candle direction), 10R or close", instruments="BTC 5m 2016-26", timeframe="5m", hold="to 16:00 ET",
         design="-0.32R (t -3.7)", held_out="-0.34R", fresh="n/a", verdict="fail", script="orb.py", notes=""),
    dict(id="O02", date="2026-09-25", family="opening range", hypothesis="ORB-15 at the US open", instruments="BTC; 9 alts 15m", timeframe="15m", hold="to 16:00 ET",
         design="-0.21R (t -2.9)", held_out="-0.28R", fresh="-0.16R (alts)", verdict="fail", script="orb.py", notes=""),
    dict(id="V01", date="2026-09-25", family="volatility breakout", hypothesis="Williams volatility breakout long (open + 0.5 x prior range), stop at the open, exit at day end", instruments="BTC 5m; 9 alts 1h", timeframe="intraday", hold="to day end",
         design="+0.01R; halves +0.33R, -0.09R", held_out="-0.05R", fresh="-0.20R (t -10.9)", verdict="fail", script="vb_pairs.py", notes=""),
    dict(id="V02", date="2026-09-25", family="volatility breakout", hypothesis="Williams volatility breakout short", instruments="as V01", timeframe="intraday", hold="to day end",
         design="-0.15R", held_out="-0.12R", fresh="-0.20R", verdict="fail", script="vb_pairs.py", notes=""),
    dict(id="P01", date="2026-09-25", family="pairs", hypothesis="Pair MAX-10 on the ratio to BTC (long/short)", instruments="ETH, SOL, XRP vs BTC; six fresh", timeframe="daily", hold="24h",
         design="+0.02R (t 2.6)", held_out="0.00R", fresh="+0.01R", verdict="fail", script="vb_pairs.py", notes="No cross-sectional edge"),
    dict(id="T09", date="2026-09-25", family="continuation", hypothesis="MAX-10 as a same-day trade (08:00 to 21:00 UTC)", instruments="as T01 (1h)", timeframe="1h", hold="13h",
         design="-0.01R", held_out="+0.04R", fresh="-0.02R", verdict="fail", script="max10_intraday.py", notes="MAX-10's edge accrues outside 08:00 to 21:00 UTC"),
    dict(id="T10", date="2026-09-25", family="continuation", hypothesis="MAX-10 with a pullback limit entry (open - 0.25 ATR)", instruments="as T09", timeframe="1h", hold="24h",
         design="0.00R", held_out="0.00R", fresh="+0.01R", verdict="fail", script="max10_intraday.py", notes=""),
    dict(id="K01", date="2026-09-25", family="stocks intraday", hypothesis="ORB-5 at the US open", instruments="TQQQ, SPXL, SOXL 5m 2020-26; 2x single-stock ETFs fresh", timeframe="5m", hold="to 16:00",
         design="-0.55R (t -8.1)", held_out="-0.59R", fresh="-0.15R", verdict="fail", script="stocks_intraday.py", notes="Costs at Bitunix stock-perp rates"),
    dict(id="K02", date="2026-09-25", family="stocks intraday", hypothesis="ORB-15 at the US open", instruments="as K01", timeframe="15m", hold="to 16:00",
         design="-0.32R", held_out="-0.33R", fresh="-0.10R", verdict="fail", script="stocks_intraday.py", notes=""),
    dict(id="K03", date="2026-09-25", family="stocks intraday", hypothesis="Intraday momentum: prior close to 10:00 sets 15:30 to 16:00 side", instruments="as K01", timeframe="5m", hold="30 min",
         design="-0.20% a trade (t -18.6)", held_out="-0.21%", fresh="-0.20%", verdict="fail", script="stocks_intraday.py", notes="Gross about zero; costs 0.18%"),
    dict(id="K04", date="2026-09-25", family="stocks overnight", hypothesis="Overnight drift: long 16:00 to 09:30", instruments="as K01", timeframe="daily", hold="overnight",
         design="-0.08% a night", held_out="+0.04%", fresh="0.00%", verdict="fail", script="stocks_intraday.py", notes=""),
    dict(id="K05", date="2026-09-25", family="stocks daily", hypothesis="MAX-10 on stocks", instruments="as K01", timeframe="daily", hold="24h",
         design="+0.04R (t 1.3)", held_out="-0.04R", fresh="+0.06R", verdict="fail", script="stocks_intraday.py", notes="Short history"),
    dict(id="K06", date="2026-09-25", family="stocks daily", hypothesis="Trend ensemble long on stocks", instruments="as K01", timeframe="daily", hold="days",
         design="+0.17R (t 2.1)", held_out="-0.16R (t -2.9)", fresh="+0.06R", verdict="fail", script="stocks_intraday.py", notes=""),
    dict(id="K07", date="2026-09-25", family="stocks daily", hypothesis="Trend ensemble short on stocks", instruments="as K01", timeframe="daily", hold="days",
         design="-0.29R (t -5.4)", held_out="-0.32R", fresh="-0.26R", verdict="fail", script="stocks_intraday.py", notes=""),
    # ---- 25 and 26 September 2026: batches 3 to 5, stock CFDs, placebo controls (harness.py table in results_table.csv) ----
    dict(id="W01", date="2026-09-25", family="window", hypothesis="MAX-10 state traded inside the morning window (08:00 to 19:00 UTC), stop 0.25 daily ATR, 2R", instruments="BTC, ETH, SOL, XRP; six fresh coins", timeframe="1h", hold="11h",
         design="-0.087R (t -2.0)", held_out="+0.057R", fresh="-0.071R", verdict="fail", script="batch3a.py", notes="Median stop 1.44% (about 38x); control, all window longs, -0.07R to -0.13R"),
    dict(id="W02", date="2026-09-25", family="window", hypothesis="MAX-10 state inside the evening window (19:00 to 08:00 UTC)", instruments="as W01", timeframe="1h", hold="13h",
         design="-0.088R (t -2.1)", held_out="-0.117R", fresh="-0.093R", verdict="fail", script="batch3a.py", notes=""),
    dict(id="W03", date="2026-09-25", family="window", hypothesis="Five or more trend components long, morning window", instruments="as W01", timeframe="1h", hold="11h",
         design="-0.009R (t -0.3)", held_out="-0.016R", fresh="-0.077R", verdict="fail", script="batch3a.py", notes=""),
    dict(id="W04", date="2026-09-25", family="window", hypothesis="Five or more trend components long, evening window", instruments="as W01", timeframe="1h", hold="13h",
         design="-0.086R (t -2.5)", held_out="-0.084R", fresh="-0.046R", verdict="fail", script="batch3a.py", notes="The daily edges do not survive a tight intraday stop"),
    dict(id="B01", date="2026-09-25", family="disproof", hypothesis="T01 and T03 robustness: walk-forward lookback, BTC regime, double costs, years", instruments="as T01", timeframe="daily", hold="as tested",
         design="MAX-10 walk-forward +0.088R (t 4.4)", held_out="double costs +0.071R (t 2.0)", fresh="double costs +0.047R (t 2.3)", verdict="supports T03",
         script="batch3a.py", notes="MAX-10 by BTC trend: up +0.103R, flat +0.048R, down -0.006R. T01 Sharpe positive every year but 2018 (-0.16)"),
    dict(id="C1a", date="2026-09-25", family="macro", hypothesis="Pre-FOMC drift, 14:00 the day before to 13:55 on the day (Lucca and Moench)", instruments="SPXL, TQQQ 5m 2020-26", timeframe="5m", hold="24h",
         design="+0.41% an event (t 2.5)", held_out="+0.05% (t 0.3)", fresh="n/a", verdict="fail", script="batch3b.py", notes=""),
    dict(id="C1b", date="2026-09-25", family="macro", hypothesis="Pre-FOMC drift on BTC", instruments="BTC Bitstamp 5m 2017-26", timeframe="5m", hold="24h",
         design="+0.51% (t 0.9)", held_out="-0.15%", fresh="n/a", verdict="fail", script="batch3b.py", notes=""),
    dict(id="C2a", date="2026-09-25", family="reversal", hypothesis="RSI-2 dips in uptrends (Connors) on leveraged ETF proxies", instruments="TQQQ, SPXL, SOXL; 14 fresh ETFs, 2020-26", timeframe="daily", hold="up to 10 days",
         design="-0.009R (t -0.1)", held_out="+0.258R (t 2.5)", fresh="+0.066R", verdict="fail", script="batch3b.py", notes="Short history; retested on 33 years as SC6"),
    dict(id="C2b", date="2026-09-25", family="reversal", hypothesis="RSI-2 dips in uptrends on crypto", instruments="BTC, ETH, SOL, XRP; six fresh", timeframe="daily", hold="up to 10 days",
         design="-0.002R", held_out="-0.054R", fresh="-0.003R", verdict="fail", script="batch3b.py", notes=""),
    dict(id="C5", date="2026-09-25", family="stocks daily", hypothesis="K05 and K06 repeated with nine more fresh ETFs", instruments="17 leveraged ETFs", timeframe="daily", hold="days",
         design="MAX-10 +0.039R (t 1.3); trend +0.165R (t 2.1)", held_out="-0.039R; -0.162R", fresh="-0.033R; -0.032R", verdict="fail", script="batch3b.py", notes="Not new variants"),
    dict(id="SC1", date="2026-09-25", family="stock CFD", hypothesis="Turn of the month on index ETFs, last day to third day", instruments="SPY, QQQ 1993-2026; 12 fresh ETFs", timeframe="daily", hold="4 days",
         design="+0.026R (t 0.9)", held_out="+0.019R", fresh="+0.013R", verdict="fail", script="stocks_cfd.py", notes="Beats other days (-0.056R) but not costs"),
    dict(id="SC2a", date="2026-09-25", family="stock CFD", hypothesis="Short UVXY while VIX/VIX3M < 0.95 (volatility carry)", instruments="UVXY 2011-26", timeframe="daily", hold="to 20 days",
         design="+0.194R (t 2.1)", held_out="+0.090R (t 1.0)", fresh="n/a", verdict="fail (positive, under t 3)", script="stocks_cfd.py", notes="10 of 13 years positive; gap-aware stops"),
    dict(id="SC2b", date="2026-09-25", family="stock CFD", hypothesis="Short UVXY while VIX/VIX3M < 0.90", instruments="as SC2a", timeframe="daily", hold="to 20 days",
         design="+0.207R (t 2.1)", held_out="+0.091R", fresh="n/a", verdict="fail", script="stocks_cfd.py", notes=""),
    dict(id="SC3", date="2026-09-25", family="stock CFD", hypothesis="Trend ensemble long on single stocks (T01 rules)", instruments="39 design, 53 fresh stocks from the Bitunix list", timeframe="daily", hold="weeks",
         design="+0.178R (t 9.2)", held_out="+0.256R (t 5.3)", fresh="+0.453R (t 6.1)", verdict="reject (survivorship)", script="stocks_cfd.py",
         notes="Random entry days did better (+0.29R, +0.53R, +0.78R): today's Bitunix list is a list of winners"),
    dict(id="SC4", date="2026-09-25", family="stock CFD", hypothesis="MAX-10 on single stocks", instruments="as SC3", timeframe="daily", hold="24h",
         design="-0.005R (t -1.5)", held_out="-0.010R", fresh="+0.002R", verdict="fail", script="stocks_cfd.py", notes="MAX-10 is crypto-specific"),
    dict(id="SC5a", date="2026-09-25", family="stock CFD", hypothesis="Weekly short-term reversal, long 3 losers and short 3 winners", instruments="as SC3", timeframe="weekly", hold="1 week",
         design="-0.007R", held_out="-0.046R (t -3.2)", fresh="-0.040R", verdict="fail", script="stocks_cfd.py", notes=""),
    dict(id="SC5b", date="2026-09-25", family="stock CFD", hypothesis="Weekly reversal only when VIX >= 20 (Nagel)", instruments="as SC3", timeframe="weekly", hold="1 week",
         design="-0.009R", held_out="-0.060R", fresh="-0.029R", verdict="fail", script="stocks_cfd.py", notes=""),
    dict(id="SC6", date="2026-09-26", family="stock CFD", hypothesis="RSI-2 dips in uptrends on index ETFs (33 years)", instruments="SPY, QQQ; 12 fresh ETFs", timeframe="daily", hold="about 4 days",
         design="+0.152R (t 3.4) at Bitunix funding", held_out="+0.138R (t 2.1)", fresh="+0.042R (t 2.4)", verdict="conditional (watch)", script="stocks_cfd.py",
         notes="Beats random uptrend days by +0.16R, +0.16R, +0.07R (t 3.5, 2.3, 3.6); fails at 0.03%/day funding and at double fees (fresh -0.009R)"),
    dict(id="SC7", date="2026-09-25", family="stock CFD", hypothesis="Index limit dip: buy limit at close - 0.5 ATR in uptrends", instruments="as SC6", timeframe="daily", hold="1 to 2 days",
         design="-0.141R (t -6.6)", held_out="-0.100R", fresh="-0.103R", verdict="fail", script="stocks_cfd.py", notes=""),
    dict(id="SC8a", date="2026-09-25", family="stock CFD", hypothesis="Event-gap continuation, longs (post-announcement drift)", instruments="as SC3", timeframe="daily", hold="10 days",
         design="+0.022R (t 0.2)", held_out="+0.166R", fresh="+0.097R", verdict="fail", script="stocks_cfd.py", notes="Random days with the same stop did as well"),
    dict(id="SC8b", date="2026-09-25", family="stock CFD", hypothesis="Event-gap continuation, both sides", instruments="as SC3", timeframe="daily", hold="10 days",
         design="-0.011R", held_out="+0.033R", fresh="+0.057R", verdict="fail", script="stocks_cfd.py", notes=""),
    dict(id="SC9a", date="2026-09-26", family="stock CFD", hypothesis="Trend ensemble long on index, sector, country and metal ETFs", instruments="SPY, QQQ, GLD, SLV; 14 fresh ETFs", timeframe="daily", hold="median 26 days",
         design="+0.245R (t 3.7) at Bitunix funding", held_out="+0.532R (t 4.2)", fresh="+0.139R (t 5.2)", verdict="beta, not an entry edge", script="batch5_etf.py",
         notes="Passes the gate and double fees, fails at 0.03%/day funding; random entry days with the same exit did better, so the return is drift plus the trailing exit"),
    dict(id="SC9b", date="2026-09-25", family="stock CFD", hypothesis="Trend ensemble long and short on ETFs", instruments="as SC9a", timeframe="daily", hold="weeks",
         design="-0.122R (t -3.2)", held_out="0.000R", fresh="-0.124R", verdict="fail", script="batch5_etf.py", notes="Shorts alone -0.24R"),
    dict(id="K08", date="2026-09-25", family="stock CFD", hypothesis="Overnight drift after a down session (Boyarchenko, Larsen and Whelan)", instruments="as SC9a", timeframe="daily", hold="overnight",
         design="-0.069R (t -9.3)", held_out="-0.066R", fresh="-0.047R", verdict="fail", script="batch5_etf.py", notes="Mean overnight move +0.058% against 0.14% costs"),
    dict(id="N1a", date="2026-09-25", family="order flow", hypothesis="Taker buy share (24h) in the top or bottom fifth, follow it for the window, stop 0.25 ATR", instruments="10 coins, Binance 1h 2022-26", timeframe="1h", hold="window",
         design="-0.069R (t -2.7)", held_out="-0.034R", fresh="-0.049R", verdict="fail", script="batch4_crypto.py", notes=""),
    dict(id="N1b", date="2026-09-25", family="order flow", hypothesis="As N1a, stop 0.5 ATR", instruments="as N1a", timeframe="1h", hold="window",
         design="-0.019R", held_out="+0.001R", fresh="-0.026R", verdict="fail", script="batch4_crypto.py", notes=""),
    dict(id="N1c", date="2026-09-25", family="order flow", hypothesis="As N1a, reversed (exhaustion)", instruments="as N1a", timeframe="1h", hold="window",
         design="-0.099R (t -3.9)", held_out="-0.120R", fresh="-0.078R", verdict="fail", script="batch4_crypto.py", notes=""),
    dict(id="N2", date="2026-09-25", family="levels", hypothesis="Round-number fade (Osler): resting limits at the nearest round levels", instruments="BTC 5m 2016-26; nine coins 1h", timeframe="5m and 1h", hold="window",
         design="-0.066R (t -5.8)", held_out="-0.076R", fresh="-0.044R", verdict="fail", script="batch4_crypto.py", notes="Half-step control -0.044R: round numbers break more often than they hold"),
    dict(id="N4", date="2026-09-25", family="breakout", hypothesis="Asia-range bracket at the 08:30 run, stop at the range midpoint", instruments="as N2", timeframe="5m and 1h", hold="to 19:00 UTC",
         design="-0.232R (t -13.7)", held_out="-0.296R", fresh="-0.365R", verdict="fail", script="batch4_crypto.py", notes=""),
    dict(id="N5", date="2026-09-25", family="reversal", hypothesis="Turtle soup (Raschke and Connors), both sides", instruments="as T01", timeframe="daily", hold="3 days",
         design="-0.169R (t -3.2)", held_out="-0.129R", fresh="-0.098R", verdict="fail", script="batch4_crypto.py", notes=""),
    dict(id="C3", date="2026-09-25", family="improvement", hypothesis="MAX-10 skipping signals when funding is in its top fifth", instruments="BTC, ETH", timeframe="daily", hold="24h",
         design="+0.119R vs +0.084R (2020-23)", held_out="+0.071R vs +0.066R (Aug 2025 on)", fresh="n/a", verdict="not adopted", script="batch4_crypto.py", notes="Small and thin"),
    dict(id="C4", date="2026-09-25", family="improvement", hypothesis="T01 trades weighted by inverse volatility", instruments="as T01", timeframe="daily", hold="weeks",
         design="Sharpe 1.40 vs 1.50", held_out="2.03 vs 1.87", fresh="1.31 vs 1.30", verdict="not adopted", script="batch4_crypto.py", notes="Mixed"),
    dict(id="PL1", date="2026-09-26", family="placebo", hypothesis="T01 against random entry days with the same trailing exit", instruments="as T01", timeframe="daily", hold="weeks",
         design="-0.08R (t -0.5)", held_out="+0.42R (t 2.2)", fresh="-0.21R (t -1.9)", verdict="T01 is beta with a trailing exit", script="placebo_crypto.py",
         notes="The expectancy comes from crypto's drift and letting winners run; the breakout entry adds nothing reliable"),
    dict(id="PL2", date="2026-09-26", family="placebo", hypothesis="MAX-10 against a long every day with the same stop and hold", instruments="as T03", timeframe="daily", hold="24h",
         design="+0.093R (t 3.8)", held_out="+0.093R (t 2.5)", fresh="+0.057R (t 2.7)", verdict="T03 is a genuine entry edge", script="placebo_crypto.py",
         notes="The only signal that beats its placebo in every set"),
]


def main() -> None:
    with (HERE / "ledger.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS); w.writeheader(); w.writerows(ENTRIES)
    passes = [e for e in ENTRIES if e["verdict"].upper().startswith("PASS")]
    lines = ["# Research ledger", "",
             "Every hypothesis tested for the sleeve, pass or fail. Generated by build_ledger.py from ledger.csv.", "",
             "**Gate:** net of fees (maker 0.02%, taker 0.06%) and slippage; longs pay funding at 0.03% a day; design t of 3 or more; the same sign in both halves; positive on the held-out period (run once) and on coins never used in design. Every variant is counted.", "",
             f"**Tested:** {len(ENTRIES)} hypotheses. **Passed:** {len(passes)} ({', '.join(e['id'] for e in passes)}), both daily-signal long trend effects. No intraday construction has passed.", "",
             "| ID | Date | Family | Hypothesis | Design | Held-out | Fresh | Verdict |", "|---|---|---|---|---|---|---|---|"]
    for e in ENTRIES:
        lines.append(f"| {e['id']} | {e['date']} | {e['family']} | {e['hypothesis']} | {e['design']} | {e['held_out']} | {e['fresh']} | {e['verdict']} |")
    (HERE / "LEDGER.md").write_text("\n".join(lines) + "\n")
    print(f"{len(ENTRIES)} entries written")


if __name__ == "__main__":
    main()
